// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEl5BYXg79EGJ9UBvF_YkbETYHldywvLQ',
    appId: '1:820203411093:web:a85cccdd648f6a5bdb2d9c',
    messagingSenderId: '820203411093',
    projectId: 'login-registration-bloc-f5f33',
    authDomain: 'login-registration-bloc-f5f33.firebaseapp.com',
    storageBucket: 'login-registration-bloc-f5f33.firebasestorage.app',
    measurementId: 'G-NW0CZRXSJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1B0LSZI7fl5F6Xv7g-bkfJhsrMq20lPc',
    appId: '1:820203411093:android:84a99a2254381229db2d9c',
    messagingSenderId: '820203411093',
    projectId: 'login-registration-bloc-f5f33',
    storageBucket: 'login-registration-bloc-f5f33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7QpnrDXXFGL_LT9G3g2ghtVGi2XJox78',
    appId: '1:820203411093:ios:e581d23264939a70db2d9c',
    messagingSenderId: '820203411093',
    projectId: 'login-registration-bloc-f5f33',
    storageBucket: 'login-registration-bloc-f5f33.firebasestorage.app',
    iosBundleId: 'com.example.loginRegistrationUserinfoBlocFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7QpnrDXXFGL_LT9G3g2ghtVGi2XJox78',
    appId: '1:820203411093:ios:e581d23264939a70db2d9c',
    messagingSenderId: '820203411093',
    projectId: 'login-registration-bloc-f5f33',
    storageBucket: 'login-registration-bloc-f5f33.firebasestorage.app',
    iosBundleId: 'com.example.loginRegistrationUserinfoBlocFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEl5BYXg79EGJ9UBvF_YkbETYHldywvLQ',
    appId: '1:820203411093:web:6b0f257d12689788db2d9c',
    messagingSenderId: '820203411093',
    projectId: 'login-registration-bloc-f5f33',
    authDomain: 'login-registration-bloc-f5f33.firebaseapp.com',
    storageBucket: 'login-registration-bloc-f5f33.firebasestorage.app',
    measurementId: 'G-9FSBSVCJ9N',
  );
}
